version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      nuget-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/Taurit.TodoistTools.CalendarProxy.UI"
    schedule:
      interval: "monthly"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    ignore:
      # ignore angular updates, which are best updated with `ng update`
      - dependency-name: "@angular/*"
      # tied to angular and often breaks if updated out of sync
      - dependency-name: "typescript"
      # peer depencdency of angular/core and breaks build if version doesn't match
      - dependency-name: "zone.js"
